server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Qwe123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  cache:
    default:
      expire-time: 7000000
    user:
      expire-time: 7000000
      name: "Cart"