server:
  port: 5555

spring:
  eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
        fetchRegistry: false
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: market-service
          uri: lb://market-service/
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market
            - JwtAuthFilter
        - id: cart-service
          uri: lb://cart-service/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart
            - JwtAuthFilter
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth
            - JwtAuthFilter
        - id: order-service
          uri: lb://order-service/
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - PrefixPath=/orders
            - JwtAuthFilter

