eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}
      fetchRegistry: false
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: market-service
          uri: lb://market-service/
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market
            - JwtAuthFilter
        - id: cart-service
          uri: lb://cart-service/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart
            - JwtAuthFilter
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth
            - JwtAuthFilter
        - id: order-service
          uri: lb://order-service/
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - PrefixPath=/orders
            - JwtAuthFilter

