version: '3'

services:
  postgres:
    container_name: postgres_auth_container
    domainname: postgresAuth
    image: postgres:13.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Qwe123"
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - spring-cloud-network

  auth-service:
    container_name: auth_ms_container
    build:
      context: ./
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      - "DB_HOST=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=Qwe123"
      - "SERVER_PORT=9000"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge

