server:
  port: 8191
  servlet:
    context-path: /orders
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: Qwe123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      group-id: "1"
    bootstrap-servers: localhost:9092