server:
  port: 8170
  servlet:
    context-path: /cart
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  cache:
    default:
      expire-time: 7000000
    user:
      expire-time: 7000000
      name: "Cart"