server:
  servlet:
    context-path: /cart
spring:
  application:
    name: cart-service
  redis:
    password:
  cache:
    default:
      expire-time: 7000000
    user:
      expire-time: 7000000
      name: "Cart"
  kafka:
    consumer:
      group-id: "1"
    bootstrap-servers: "kafka:9092"
eureka:
  instance:
    hostname: cart-service
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka}
      fetchRegistry: false